export const ADD_RESTAURANT_DATA = 'ADD_RESTAURANT_DATA';
export const ADD_DATA_LOADER = 'ADD_DATA_LOADER';
export const ADD_RESTAURANTS_DATA = 'ADD_RESTAURANTS_DATA';
export const ADD_CATEGORY_DATA = 'ADD_CATEGORY_DATA';
export const ADD_DISTANCE = 'ADD_DISTANCE';




